# Fill out missing config values
# Rename to config.yml

reddit:
  user: [USER]
  password: [PASSWORD]

sources:
  - name: Baseball Reference
    abbrv: bref
    player_link: http://www.baseball-reference.com/pl/player_search.cgi?search=
    mlb_team_link: http://www.baseball-reference.com/pl/player_search.cgi?search= 

  - name: Fangraphs
    abbrv: fg
    player_link: http://www.fangraphs.com/players.aspx?lastname=
    mlb_team_link:

teams:
  mlb:
    - angels 
    - astros 
    - athletics 
    - blue jays 
    - braves 
    - brewers 
    - cardinals 
    - cubs 
    - diamondbacks 
    - dodgers 
    - giants 
    - indians 
    - mariners 
    - marlins 
    - mets 
    - nationals 
    - orioles 
    - padres 
    - phillies 
    - pirates 
    - rangers 
    - rays 
    - red sox 
    - reds 
    - rockies 
    - royals 
    - tigers 
    - twins 
    - white sox 
    - yankees